/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

public class App {

    public static void main(String[] args) {

        Ponto a = new Ponto(5, 10);
        Ponto b = new Ponto(5, 10);

        System.out.println(a.toString());
        System.out.println(b.toString());
        System.out.println(a.calcularDistancia(b));

        a.setX(6);
        System.out.println(a.toString());




    }
}
