/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

public class App {

    public static void main(String[] args) {

//        Carro fusca = new Carro();
//        Carro ferrari = new Carro();
//
//        fusca.definirVelocidade(10);
//        ferrari.definirVelocidade(120);
//
//        System.out.println("Velocidade Fusca: "+ fusca.obterVelocidade() + " Km/h");
//        System.out.println("Velocidade Ferrari: "+ ferrari.obterVelocidade() + " Km/h");


        Carro fusca = new Carro();
        fusca.definirModelo("fusca");
        fusca.definirCor("azul");
        fusca.definirVelocidade(10);

        Carro gol = new Carro();
        gol.definirModelo("gol");
        gol.definirCor("verde");
        gol.definirVelocidade(30);

        System.out.println(fusca.obterModelo()+ " "+fusca.obterCor()+" está a "+ fusca.obterVelocidade() + "Km/h");
        System.out.println(gol.obterModelo()+ " "+ gol.obterCor()+" está a "+ gol.obterVelocidade() + "Km/h");





    }
}
