/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

public class App {

    public static void main(String[] args) {

    //interface com usuario

        Carro c = new Carro();

        c.acelerar(100);
        c.acelerar(50);
        c.acelerar(150);

        System.out.println(c.obterVelocidade());

        c.frear(30);
        c.frear(90);
        c.frear(150);

        System.out.println(c.obterVelocidade());
        System.out.println(" ");


//-------------------------------------------------------------------------------


        Pessoa a = new Pessoa("Ana Clara da Silva", "123.134.645-34");
//        a.definirNome("Ana Clara da Silva");
//        a.definirCPF("123.134.645-34");

        Pessoa b = new Pessoa("João Antônio Guimarães", "836.236.765-56" );
//        b.definirNome("João Antônio Guimarães");
//        b.definirCPF("836.236.765-56");

        Pessoa d = new Pessoa();

        //melhor obter individualmente
        System.out.println(a.imprimir());
        System.out.println(b.imprimir());





    }
}
