/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

public class App {

    public static void main(String[] args) {

        //int moeda = -1;
       // do {
       //     System.out.println("Digite o valor da sua moeda: " + args[0]);
       //     int soma = 0;
      //      moeda = Integer.parseInt(args[0]);
      // } while (moeda != 0);

        int moeda;
        int soma=0;
        int valor;

        System.out.println("Digite o valor da sua moeda: " + args[0]);
        moeda = Integer.parseInt(args[0]);

        soma += moeda;







        int[] moedas = new int[6];










    }
}
