/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

import edu.princeton.cs.algs4.Draw;

public class App {

    private Draw draw;

    public App() {
        this.draw = new Draw();
    }


    public static void main(String[] args) {


        App app = new App();


    }
}
