/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ads.poo;


import edu.princeton.cs.algs4.Draw;

import java.awt.*;

public class App {

     Draw draw;

    public App() {
        this.draw = new Draw();
        draw.setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);
        this.draw.setCanvasSize(1000, 600);
        this.draw.setXscale(0, 1000);
        this.draw.setYscale(0, 600);
    }


    public static void main(String[] args) {

        App app = new App();

        Grade grade = new Grade(200, 120, Color.black);

        Navio navio = new Navio(360, 160, false, 4);

        grade.desenhar(app.draw, Color.red);

        navio.desenhar(app.draw, Color.BLUE);











    }
}
