/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

import ads.poo.produtos.Dimensao;
import ads.poo.produtos.SemFio;
import ads.poo.produtos.Telefone;

public class App {


    public static void main(String[] args) {

        Telefone tel = new Telefone(12, "aa", "b", 5, new Dimensao(12, 334, 56));
        SemFio sf = new SemFio( 12, "grbts", "fsers", 5, new Dimensao(12, 334, 56), 12, 34, 54);

        System.out.println(tel.imprimirDados());

        System.out.println(sf.imprimirDados());









    }
}
