/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

public class App {
    public static void main(String[] args) {


        Navio a = new Navio(5, 3, 5, true, 'S');

        a.setX(7);

        System.out.println(a.verificarAfundou());
        System.out.println(a.getLetra());
        System.out.println(a.getX());

        System.out.println(a.atirarEm(7,5));










    }
}
