
/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

import java.util.Scanner;

public class App {
    public static void main(String[] args) {

        Scanner leitor = new Scanner(System.in);

        String[] charValido = {".", "P", "E", "S", "N", "C"};
        String[][] mapa = new String[10][10];
        int[] contadores = new int[5];
        int contador = 0;


        for (int i = 0; leitor.hasNext(); i++) {
            String linhaOriginal = leitor.nextLine();
            String[] linha = linhaOriginal.split(" ");
            if (i >= 10) {
                System.out.println("O mapa possui mais de 10 linhas");
                break;
            }
            if (linha.length == 10) {
                for (int j = 0; j < linha.length; j++) {
                    for (int k = 0; k < charValido.length; k++) {
                        if (!linha[j].equals(charValido[k])) {
                            contador++;
                        }
                    }
                    if (contador >= 6) {
                        System.out.println("O caracter " + linha[j] + " na posição (" + (j + 1) + "," + (i + 1) + ") é um caracter inválido");
                        contador = 0;
                    } else {
                        mapa[i][j] = linha[j];
                        contador = 0;
                    }
                }
            } else {
                System.out.println("Tamanho de mapa inválido");
            }
        }


        for (int i = 0; i < contadores.length; i++) {
            for (int j = 0; j < mapa.length; j++) {
                for (int k = 0; k < mapa.length; k++) {
                    if (charValido[i + 1].equals(mapa[j][k])) {
                        contadores[i]++;
                    }
                }
            }
        }


        if (contadores[0] != 5) {
            System.out.println("A quantidade de P's está errada, existem " + contadores[0] + " P's quando deveriam existir 5");
        }
        if (contadores[1] != 4) {
            System.out.println("A quantidade de E's está errada, existem " + contadores[1] + " E's quando deveriam existir 4");
        }
        if (contadores[2] != 3) {
            System.out.println("A quantidade de S's está errada, existem " + contadores[2] + " S's quando deveriam existir 3");
        }
        if (contadores[3] != 2) {
            System.out.println("A quantidade de N's está errada, existem " + contadores[3] + " N's quando deveriam existir 2");
        }
        if (contadores[4] != 3) {
            System.out.println("A quantidade de C's está errada, exitem " + contadores[4]+ " C's quando deveriam existir 3");
        }







//verificar se os navios estão alinhados ou com furos


        for (int i = 0; i < mapa.length; i++) {
            for (int j = 0; j < mapa[i].length; j++) {
                String caracterAnterior = mapa[i][j];
                boolean sequencia = true;
                //horizontal
                for(int k =j;  k< mapa[i].length; k++){
                    if(mapa[j][i].equals(".") && caracterAnterior.equals(".")){
                        sequencia = false;
                        System.out.println("letra com espaco horizonralmente");
                        break;
                    }
                }
                if(!sequencia){
                    if(mapa[j][i].equals(".") && caracterAnterior.equals(".")){
                        sequencia = false;
                        System.out.println("letra com espaco verticalmente");
                        break;
                    }
                }





               // if (!mapa[j + 1][i].equals(charValido[j + 1])) {
                //    System.out.println("Tem letra separada analisando as colunas ");
               // } else {
                //    if (!mapa[j][i + 1].equals(charValido[j + 1])) {
                 //       System.out.println("Tem letra separada analisando as linhas ");
                 //   }
               // }

            }
        }



        //imprimir mapa
        for (int i = 0; i < mapa.length; i++) {
            for (int j = 0; j < mapa.length; j++) {
                System.out.print(mapa[i][j]);
            }
            System.out.println(" ");
        }
    }
}

