/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

import edu.princeton.cs.algs4.Draw;

import java.awt.*;
import java.awt.event.MouseEvent;

public class App {
    private Draw draw;

    public App(){
        this.draw = new Draw();
        this.draw.setCanvasSize(400, 600);
        this.draw.setXscale(0, 400);
        this.draw.setYscale(0, 600);
    }



    public void quadrado(){

    }

    public static void main(String[] args) {

        App app = new App();

        app.quadrado();

//        app.draw.filledCircle(300, 150, 100);
//
        Color vermelho = new Color(200, 25, 30);
        Color verde= new Color(50, 160, 65);
//
//        app.draw.setPenColor(vermelho);
//
//        app.draw.filledRoundRectangle(100, 134, 91, 54, 98, 230);
//
//        Circulo a = new Circulo(100, 90, 43, vermelho);
//
//         a.desenhar(app.draw);
//
//        Circulo b = new Circulo(150, 130, 43, azul);
//
//        b.desenhar(app.draw);

//        Quadriculado d = new Quadriculado(200, 100, 40, 4, 3, Draw.BLACK);
//
//        d.desenhar(app.draw);

        Quadriculado quadriculado = new Quadriculado(0, 0, 30, 70, 30, Draw.GRAY);
        Ifsc ifscCirc = new Ifsc(60, 510, 45, vermelho); //corrigir esse raio no construtor
        Ifsc ifscQuad1 = new Ifsc(180, 510, 0, verde);
        Ifsc ifscQuad2 = new Ifsc(300, 510, 0, verde);
        Ifsc ifscQuad3 = new Ifsc(60, 390, 0, verde);
        Ifsc ifscQuad4 = new Ifsc(180, 390, 0, verde);
        Ifsc ifscQuad5 = new Ifsc(60, 270, 0, verde);
        Ifsc ifscQuad6 = new Ifsc(180, 270, 0, verde);
        Ifsc ifscQuad7 = new Ifsc(300, 270, 0, verde);
        Ifsc ifscQuad8 = new Ifsc(60, 150, 0, verde);
        Ifsc ifscQuad9 = new Ifsc(180, 150, 0, verde);


        quadriculado.desenharQuadriculado(app.draw);

        ifscCirc.desenharCirculo(app.draw);
        ifscQuad1.desenharQuadrados(app.draw);
        ifscQuad2.desenharQuadrados(app.draw);
        ifscQuad3.desenharQuadrados(app.draw);
        ifscQuad4.desenharQuadrados(app.draw);
        ifscQuad5.desenharQuadrados(app.draw);
        ifscQuad6.desenharQuadrados(app.draw);
        ifscQuad7.desenharQuadrados(app.draw);
        ifscQuad8.desenharQuadrados(app.draw);
        ifscQuad9.desenharQuadrados(app.draw);











    }
}
