/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

import edu.princeton.cs.algs4.Draw;

public class App {

    public static void main(String[] args) {

        Draw draw = new Draw();

        draw.setPenColor(Draw.BOOK_BLUE);
        draw.text(0.5, 0.5, "Thays");

        draw.setPenColor(Draw.RED);
        draw.line(.1, .1, .3, .3);

        draw.filledCircle(.7, .7, .2);

       

    }
}
