/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.List;

public class App {


    public static void main(String[] args) {

        int[] diasPOO = {3, 5};

        DiasDaSemana[] aulas = {ads.poo.DiasDaSemana.TER, ads.poo.DiasDaSemana.QUI};

//        //3, 5
//        for(int d: diasPOO){
//            System.out.println(d);
//        }
//
//        //TER QUI
//        for(DiasDaSemana dias : aulas){
//            System.out.println(dias);
//        }

        //3
        int disco = aulas[0].id;

        DiasDaSemana relatorio = ads.poo.DiasDaSemana.getById(disco);

        if (relatorio!=null){
            System.out.println(relatorio);
        }


        switch (relatorio){
            case DOM -> System.out.println("não tem aula");
            case SAB -> System.out.println("alguns tem aula");
            default -> System.out.println("pode ter aula");
        }

        //Montar o baralho
        List<Carta> baralho = new ArrayList<>();

        for(Naipe naipe : Naipe.values()){
            for(ValoresCartas valor : ValoresCartas.values()){
                baralho.add(new Carta(naipe, valor));
            }
        }
        for(Carta c : baralho){
            System.out.println(c);
        }

        Collections.shuffle(baralho);
        for(Carta c : baralho){
            System.out.println(c);
        }






    }
}
