/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

public class App {

    public static void main(String[] args){

        Horarios a = new Horarios();
        Horarios b = new Horarios();

        b.setHora(22);
        b.setMinuto(87);


        a.setHora(1);
        a.setSegundo(1);

        b.setHora(21);
        b.setMinuto(47);
        b.setSegundo(12);


        System.out.println(a.retornarHorarioEmSegundos());
        System.out.println(a.subtrairHorarios(b));
        System.out.println(b.toString());
        System.out.println(b.setHora(3) + " "+ b.toString());
        System.out.println(b.setMinuto(0) + " "+ b.toString());
        System.out.println(b.setSegundo(-7) + " "+ b.toString());
        System.out.println(b.escreverExtenso());


    }
}
