/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

import ads.poo.JavaEmpires.Aldeao;
import ads.poo.JavaEmpires.Arqueiro;
import ads.poo.JavaEmpires.Cavaleiro;
import ads.poo.JavaEmpires.Personagem;
import jdk.jfr.Percentage;
import org.checkerframework.checker.units.qual.C;

import java.util.ArrayList;

public class App {


    public static void main(String[] args){

        Aldeao a = new Aldeao(25, 1, 0.8);
        Cavaleiro c = new Cavaleiro(50, 3, 2);
        Arqueiro arq = new Arqueiro(35, 2,1);

        ArrayList<Personagem> bonecos = new ArrayList<>();
        bonecos.add(a);
        bonecos.add(c);
        bonecos.add(arq);


        //fazer
        for(Personagem pers : bonecos){
            System.out.println();

        }


    }

}
